# Generated by Django 5.1.4 on 2025-01-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userRole',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
