# Generated by Django 5.1.4 on 2025-01-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userRole',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
