# Generated by Django 5.1.4 on 2025-01-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_profile_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pdf_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
