# Generated by Django 5.1.4 on 2025-01-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pdf_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
