# Generated by Django 5.1.4 on 2025-02-18 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField()),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(choices=[('mattina', 'Mattina'), ('pomeriggio', 'Pomeriggio'), ('sera', 'Sera'), ('notturno', 'Notturno')], max_length=10)),
                ('salary', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.profile')),
            ],
        ),
    ]
