# Generated by Django 5.1.4 on 2025-02-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_comune_profile_denominazione_farmacia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='place',
        ),
    ]
