# Generated by Django 5.1.4 on 2025-03-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile_reset_token_profile_reset_token_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy_id', models.AutoField(db_column='PharmacyID', primary_key=True, serialize=False)),
                ('pharmacy_name', models.TextField(db_column='PharmacyName')),
                ('provincia', models.TextField(db_column='Provincia')),
                ('address', models.TextField(db_column='Address')),
                ('phone', models.TextField(blank=True, db_column='Phone', null=True)),
                ('lat', models.DecimalField(blank=True, db_column='Lat', decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, db_column='Lng', decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'api_pharmacies',
            },
        ),
    ]
