# Generated by Django 5.1.4 on 2025-03-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pharmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='time',
        ),
        migrations.AddField(
            model_name='offer',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
