# Generated by Django 5.1.4 on 2025-03-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_offer_time_offer_date_from_offer_date_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.DecimalField(blank=True, db_column='Lat', decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lng',
            field=models.DecimalField(blank=True, db_column='Lng', decimal_places=6, max_digits=9, null=True),
        ),
    ]
