# Generated by Django 5.1.4 on 2025-04-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_profile_lat_profile_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('farmacista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='api.profile')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='api.offer')),
            ],
            options={
                'unique_together': {('offer', 'farmacista')},
            },
        ),
    ]
