# Generated by Django 5.1.4 on 2025-04-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='indirizzo_farmacia',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
