# Generated by Django 5.1.4 on 2025-04-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_profile_indirizzo_farmacia_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
