# Generated by Django 5.1.4 on 2025-05-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_profile_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comune_farmacia',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
