# Generated by Django 5.1.4 on 2025-05-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_comune_farmacia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='salary',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
