# Generated by Django 5.1.4 on 2025-05-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='communicationConsent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferredRegion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacyPolicyConsent',
            field=models.BooleanField(default=True),
        ),
    ]
