# Use official Python image
FROM python:3.11

# Set working directory
WORKDIR /app

# Copy dependencies files
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port
EXPOSE 8000

# Run Django server
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi"]


